name: Deploy Package

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build package
      run: npm run build

    - name: Publish to npm
      run: npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}